services:
  - type: web
    name: youtube-downloader-app-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
